spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin //Apenas teste
    password: admin //Apenas teste
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

api:
  security:
    token:
      secret: "ChaveSecreta" //Apenas teste
